### ISSUE TITLE
Support for YAML files?

### ISSUE THREAD

**Issue by lunchmenutoday** [madskristensen/RainbowBraces#30]
I'm trying to get it to work with YAML files without any luck.

Not sure if this is a bug or by design.

YAML snippet with parenthesis:

```
variables:
  BuildConfiguration: "Release"
  nugetConfigPath: "nuget.Config"
  deployOutput: "$(Build.ArtifactStagingDirectory)/Install/Application"
```
